apiVersion: v1
kind: Namespace
metadata:
  name: nginx-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-statefulset
  namespace: nginx-statefulset
spec:
  serviceName: nginx
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              name: web
          resources:
            requests:
              cpu: 300m
              memory: "300Mi"
            limits:
              cpu: 300m
              memory: "300Mi"
          command:
            - "/bin/sh"
            - "-c"
            - printenv > /mnt/azuredisk/printenv.txt; while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 60; done
          volumeMounts:
            - name: data
              mountPath: /mnt/azuredisk
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: managed-csi # default
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-statefulset-svc
#   labels:
#     app: nginx
# spec:
#   ports:
#   - port: 80
#     name: web
#   clusterIP: None
#   selector:
#     app: nginx
