apiVersion: v1
kind: Pod
metadata:
  name: mssql-tools
spec:
  containers:
  - name: mssql-tools
    image: mcr.microsoft.com/mssql-tools
    args: [/bin/sh, -c, 'while true; do echo "$(date)"; sleep 10; done']